apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress/http: "true"
  name: nginx
spec:
  selector:
    run: nginx
  type: ClusterIP
  ports:
    - port: 80        # 本 Service 的端口
      targetPort: 80  # 容器端口
